name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest  # Change to windows-latest for Windows

    steps:
    - uses: actions/checkout@v3

    - name: Set up GCC
      uses: msys2/setup-msys2@v2

    - name: Install GCC
      run: pacman --noconfirm -S mingw-w64-x86_64-gcc

    - name: Build and Run
      run: |
        gcc -o main.exe *.c
        ./main.exe
        rm main.exe
