name: Compile Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up MinGW
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
        architecture: "x64"

    - name: Install Cygwin
      run: |
        choco install cygwin -y

    - name: Source Chocolatey Profile
      run: |
        Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
        refreshenv

    - name: Install GCC and Make with Cygwin
      run: |
        "C:\tools\Cygwin\setup-x86_64.exe" -q -P gcc-core
        "C:\tools\Cygwin\setup-x86_64.exe" -q -P make

    - name: Build
      run: make calculator.exe

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: calculator
        path: calculator.exe
