name: Compile Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up MinGW
      uses: actions/setup-python@v2
      with:
        python-version: "3.x" # Choose the appropriate version
        architecture: "x64"

    - name: Install Cygwin
      run: |
        choco install cygwin -y

    - name: Source Chocolatey Profile
      run: |
        Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1

    - name: Install GCC and Make with Cygwin
      run: |
        Start-Process -Wait -FilePath "C:\tools\cygwin\setup-x86_64.exe" -ArgumentList "--quiet-mode --packages gcc-core,make"

    - name: Build
      run: make calculator.exe

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: calculator
        path: calculator.exe
