name: Build C File /w Windows

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up GCC
      uses: mattn/gof@v2
      with:
        version: latest

    - name: Compile C Files
      run: |
        gcc -o main.exe *.c

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: main-exe
        path: main.exe
